config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq", as: :sidekiq

  resources :users, only: [:create, :update] do
    collection { post :import }
  end
  devise_scope :user do
    devise_for :users, :controllers => {:registrations => "my_devise/registrations"}
    resources :users, except: [:create, :update]

    
    get "/users/sign_up",  :to => 'welcomes#index'
   
    authenticated :user do
      root 'welcomes#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end   
  end

  get 'enable/:id' => 'users#enable', as: 'enable'
  get 'disable/:id' => 'users#pre_disable', as: 'pre_disable'
  post 'disable/:id' => 'users#disable', as: 'disable'
  get '/users/role/:title', to: 'users#users_by_role', as: :users_by_role

  resources :companies

  root 'welcomes#index'

  get '/export' => 'welcomes#export', as: 'export'
  get '/en-cours-developement' => 'welcomes#en_cours_devlopement', as: 'en_cours_devlopement'

  get '/start_load' =>  'load_updated_files#start_load', as: 'start_load'

  resources :fonctional_manager_externs do
    collection { post :import }
  end

  resources :furloughs
  get 'validate/:id' => 'furloughs#validate', as: 'validate'
  get 'approuve/:id' => 'furloughs#valide_fc', as: 'valide_fc'
  get 'in_progress/:id' => 'furloughs#in_progress', as: 'in_progress'
  get 'soumettre/:id' => 'furloughs#soumettre', as: 'soumettre'
  get 'mes-congés' => 'furloughs#furloughs_administration', as: 'furloughs_administration'
  get 'congé/:id' => 'furloughs#show_administration', as: 'show_administration'
  get 'refuse/:id' => 'furloughs#pre_refuse', as: 'pre_refuse'
  post 'refuse/:id' => 'furloughs#refuse', as: 'refuse'
  get 'cancel/:id' => 'furloughs#pre_cancel', as: 'pre_cancel'
  post 'cancel/:id' => 'furloughs#cancel', as: 'cancel'
  get 'print/:id' => 'furloughs#to_print', as: 'print'
  get 'findtypefurlough/:id' => 'furloughs#find_furlough_type', as: 'find_furlough_type'
  get 'getitemtohiligh/' => 'furloughs#get_item_to_hiligh', as: 'get_item_to_hiligh'
  get 'findfonctionalmanagerid/:name' => 'furloughs#find_fonctional_manager_id', as: 'find_fonctional_manager_id'
  get 'finduserid/:name' => 'furloughs#find_user_id', as: 'find_user_id'
  get 'findlinemanagerid/:name' => 'furloughs#find_line_manager_id', as: 'find_line_manager_id'
  get 'discontinuity/:id' => 'furloughs#pre_discontinuity', as: 'pre_discontinuity'
  post 'discontinuity/:id' => 'furloughs#discontinuity', as: 'discontinuity'
  get 'regularized/:id' => 'furloughs#pre_regularized', as: 'pre_regularized'
  post 'regularized/:id' => 'furloughs#regularized', as: 'regularized'
  get 'stop/:id' => 'furloughs#pre_stop', as: 'pre_stop'
  post 'stop/:id' => 'furloughs#stop', as: 'stop'
  get 'duration_hour_taken/:user_id/:start/:hour_start/:end/:hour_end' => 'furloughs#duration_hour_taken', as: 'duration_hour_taken'
  get 'duration_taken/:start/:hour_start/:end/:hour_end' => 'furloughs#durations_taken', as: 'duration_taken'

  resources :furlough_types do
    collection { post :import }
  end
  get 'enablefurloughtype/:id' => 'furlough_types#enable_furlough_type', as: 'enable_furlough_type'
  get 'disablefurloughtype/:id' => 'furlough_types#disable_furlough_type', as: 'disable_furlough_type'


  resources :offs do
    collection { post :import }
  end
  get 'adjust/:id' => 'offs#pre_adjust', as: 'pre_adjust'
  post 'adjust/:id' => 'offs#adjust', as: 'adjust'

  resources :additional_hours  
  get 'soumettreHeuresSup/:id' => 'additional_hours#soumettre_additional_hour', as: 'soumettre_additional_hour'
  get 'mes-heures-sup' => 'additional_hours#additional_hours_administration', as: 'additional_hours_administration'
  get 'period/:additional_hour_date' => 'additional_hours#get_period', as: 'get_period'
  get 'days_of_input_form/:period' => 'additional_hours#get_days_of_input_form', as: 'get_days_of_input_form'
  get 'valid_hours/:start/:hour_start/:end/:hour_end' => 'additional_hours#get_valid_hours', as: 'get_valid_hours'
  get 'export-heures-sup' => 'additional_hours#pre_export_additional_hours', as: 'pre_export_additional_hours'
  get 'export-heures-sup-lolo' => 'additional_hours#export_additional_hours', as: 'export_additional_hours'

  resources :autorizations 
  get 'soumettreAuthorization/:id' => 'autorizations#soumettre_autorization', as: 'soumettre_autorization'
  get 'mes-authorisations' => 'autorizations#authorizations_administration', as: 'authorizations_administration'
  get 'authorization_hour_taken/:user_id/:date/:start_hour/:end_hour' => 'autorizations#duration_hour_taken_of_authorization', as: 'duration_hour_taken_of_authorization'
  get 'export-authorizations' => 'autorizations#pre_export_authorizations', as: 'pre_export_authorizations'
  get 'export-authorizations-lolo' => 'autorizations#export_authorizations', as: 'export_authorizations'
  get 'recovered/:id' => 'autorizations#pre_recovered', as: 'pre_recovered'
  post 'recovered/:id' => 'autorizations#recovered', as: 'recovered'
  post 'create_for_a_collaborator' => 'autorizations#create_for_a_collaborator', as: 'create_for_a_collaborator'
  post 'create_for_himself' => 'autorizations#create_for_him_self', as: 'create_for_him_self'
  get 'printauthorisation/:id' => 'autorizations#to_print_authorisation', as: 'to_print_authorisation'
  get 'validateAuthorization/:id' => 'autorizations#validate_autorization', as: 'validate_autorization'
  get 'refuseAuthorization/:id' => 'autorizations#pre_refus', as: 'pre_refus'
  post 'refuseAuthorization/:id' => 'autorizations#refus_autorization', as: 'refus_autorization'

  resources :absence_types

  resources :absences
  get 'export-absences' => 'absences#pre_export_absences', as: 'pre_export_absences'
  get 'export-absences-lolo' => 'absences#export_absences', as: 'export_absences'

  resources :formation_types

  resources :formations

  resources :interns

  resources :certificate_requests
  get 'printAttestation/:id' => 'certificate_requests#to_print', as: 'print_attestation'
  get 'mes-demandes-attestations' => 'certificate_requests#certificate_requests_administration', as: 'certificate_requests_administration'
  get 'validate-attestation/:id' => 'certificate_requests#validate_certificate', as: 'validate_certificate'
  get 'certificate/:id' => 'certificate_requests#pre_certificate', as: 'pre_certificate'
  post 'certificate/:id' => 'certificate_requests#certificate', as: 'certificate'
  get 'refus-certificate/:id' => 'certificate_requests#pre_refus_certificate', as: 'pre_refus_certificate'
  post 'refuscertificate/:id' => 'certificate_requests#refus_certificate', as: 'refus_certificate'

  resources :projects
  get 'deleteproject/:id' => 'projects#delete_project', as: 'delete_c'
  get 'disableproject/:id' => 'projects#disable_project', as: 'disable_project'
  get 'enableproject/:id' => 'projects#enable_project', as: 'enable_project'
  get 'findprojectid/:name' => 'projects#find_project_id', as: 'find_project_id'
  get 'unarchiveproject/:id' => 'projects#unarchive_project', as: 'unarchive_project'

  resources :affectations
  get 'disaffectation/:id' => 'affectations#pre_disaffectation', as: 'pre_disaffectation'
  post 'disaffectation/:id' => 'affectations#disaffectation', as: 'disaffectation'
  get 'mes-affectations' => 'affectations#mes_affectations', as: 'mes_affectations'
  get 'disaffectation/:user_id/:project_id' => 'affectations#disaffectation_through_project', as: 'project_disaffectation'

  resources :costs
  get 'archivedcost' => 'costs#archived_cost', as: 'archived_cost'
  get 'disablecost/:id' => 'costs#disable_cost', as: 'disable_cost'
  get 'enablecost/:id' => 'costs#enable_cost', as: 'enable_cost'
  get 'findcostid/:name' => 'costs#find_cost_id', as: 'find_cost_id'
  get 'deletecost/:id' => 'costs#delete_cost', as: 'delete_cost'
  get 'unarchivecost/:id' => 'costs#unarchive_cost', as: 'unarchive_cost'
  get 'deleteproject/:id' => 'costs#delete_project', as: 'delete_project'

  resources :notes
  get 'mes-notes' => 'notes#mes_notes', as: 'mes_notes'
  get 'projects-by-user/:name' => 'notes#project_users', as: 'project_users'

  resources :stop_actions do
    collection { post :import }
  end

  resources :grounds do
    collection { post :import }
  end

  resources :user_confs
  
  resources :template_attestations

  resources :journals

  resources :settings
end

app/models/autorization.rb
class Autorization < ApplicationRecord
  serialize :history, Array
  
  acts_as_tenant :company
  belongs_to :user

  enum status: {
    created: 1,
    encours: 2,
    soumis: 3,
    aprouved: 4,
    refuse: 5
  }

  scope :count_authorisations, lambda{|month, user_id| where('EXTRACT(MONTH FROM autorizations.date) = ? AND autorizations.user_id = ?', month, user_id).where.not(status: 5)}
  scope :filter_by_status, -> (status) { where('autorizations.status = ?', status) }
  scope :filter_by_all_status, -> (status) { where status: status }
  scope :filter_by_sup_date, -> (date) { where("autorizations.date > ?", date) }
  scope :filter_by_inf_date, -> (date) { where("autorizations.date < ?", date) }
  scope :filter_by_egal_date, -> (date) { where("autorizations.date like ?", date) }
  scope :filter_by_recovery_method, -> (recovery_method) { where("autorizations.recovery_method like ?", recovery_method)}
  scope :filter_by_all_recovery_method, -> (recovery_methods) { where recovery_method: recovery_methods }



  def self.get_hour_authorization_duration(d1, h1, h2)

    if (Furlough.is_week_day(d1.to_date) == true || Off.is_off(d1.to_date) == true)
      count_hour_furlough = 0
    elsif (Furlough.is_week_day(d1.to_date) == false || Off.is_off(d1.to_date) == false) 
      if (h1.split(/: */).first.to_i < 13) && (h2.split(/: */).first.to_i > 13)
        count_hour_furlough =  h2.split(/: */).first.to_i - h1.split(/: */).first.to_i - 2
      elsif (h1.split(/: */).first.to_i > 13) && (h2.split(/: */).first.to_i < 13)
        count_hour_furlough = 0 
      elsif (h1.split(/: */).first.to_i > 13) && (h2.split(/: */).first.to_i > 13)
        if h1.split(/: */).first.to_i > h2.split(/: */).first.to_i
          count_hour_furlough = 0
        else
          count_hour_furlough =  h2.split(/: */).first.to_i - h1.split(/: */).first.to_i
        end
      elsif (h1.split(/: */).first.to_i < 13) && (h2.split(/: */).first.to_i < 13)
        if h1.split(/: */).first.to_i > h2.split(/: */).first.to_i
          count_hour_furlough = 0
        else
          count_hour_furlough =  h2.split(/: */).first.to_i - h1.split(/: */).first.to_i
        end
      end
    end
   
    return count_hour_furlough
  end

  def self.custom_finder(date, start_hour, end_hour, user_id)
    authorization = Autorization.find_by(date: date, start_hour: start_hour, end_hour: end_hour, user_id: user_id)
    if authorization.present?
     return true
    else
      return false
    end
  end

  def self.search(params)     
    where("title LIKE ?", "%#{params[:search]}%") if params[:search].present? 
  end

end

app/helpers/autorizations_helper.rb
module AutorizationsHelper
end

app/views/autorizations/_pre_export_authorizations.html.erb
<!-- Modal -->
<div class="modal fade" id="export_autorization" role="dialog">
    <%= form_tag export_authorizations_path(format: :xlsx), :method => 'get' do %>
      <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                 <h4 class="modal-title" id="myLargeModalLabel">Filtre du rapport</h4>
                 <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-6">
                        <%= label_tag "Date d'authorisation" %>
                        <%= date_field_tag :date_authorization, class:"form-control" %>
                    </div>
                    <div class="col-6">
                        <%= label_tag 'Opérateur Date' %>
                        <%= select_tag :oppeateur_date, options_for_select(['Supérieure que','Inférieure que','Égale']), class:"form-control" %>
                    </div> 
                </div>
                <br>
                <div class="row">
                    <div class="col-12">
                        <%= label_tag "Statut des autorisations" %>
                        <%= select_tag :status_authorization, options_for_select(['Tous', 'Enregisté','En cours','Soumis','Validé','Refusé']), class:"form-control" %>
                    </div> 
              
                    <div class="col-12">
                        <%= label_tag "Méthode de récuperation" %>
                        <%= select_tag :recovery_method, options_for_select(['Tous', 'Répartition des heures sur les autres jours travaillés de la semaine', 'Retrancher de mon solde de congé']), class:"form-control" %> 
                    </div>
                </div>
            </div>
            
            <div class="modal-footer">
                <button type="submit" class="btn btn-raised btn-success"> Rapport</button>
            </div>
        </div>
      </div>
    <% end %>
</div>
 

app/views/autorizations/_pre_recovered.html.erb
<!-- Modal -->
<div class="modal fade" id="recovered_autorization" role="dialog">
    <%= simple_form_for(@autorization, as: :autorization, method: :post, url: recovered_path) do |f| %>
      <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                 <h4 class="modal-title" id="myLargeModalLabel">Traiter cette athorisation</h4>
                 <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="form-group col-md-12 legend">
                        <%= f.input :history_date, label: "Date de recouvrement", html5: true, required: true, hint: "Le date de recouvrement dois étre mentionné!" %>
                    </div>
                </div>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="form-group col-md-12 legend">
                        <%= f.input :volume, label: "Volume a régulariser", required: true, hint: "Le volume a régulariser dois étre mentionné!" %>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <%= f.button :submit, "Traiter", data: { confirm: 'Etes vous sur?' }, class: 'btn btn-raised btn-success' %>
                <button type="button" class="btn btn-raised btn-danger" data-dismiss="modal">Fermer</button>
            </div>
        </div>
      </div>
    <% end %>
</div>

app/views/autorizations/_pre_refus.html.erb
<!-- Modal -->
<div class="modal fade" id="refus_autorization" role="dialog">
    <%= simple_form_for(@autorization, as: :autorization, method: :post, url: refus_autorization_path) do |f| %>
      <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                 <h4 class="modal-title" id="myLargeModalLabel">Traiter cette athorisation</h4>
                 <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="form-group col-md-12 legend">
                        <%= f.input :refus_motif, label: "Motif de refus", required: true, hint: "Le motif de refus dois étre mentionné!" %>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <%= f.button :submit, "Traiter", data: { confirm: 'Etes vous sur?' }, class: 'btn btn-raised btn-success' %>
                <button type="button" class="btn btn-raised btn-danger" data-dismiss="modal">Fermer</button>
            </div>
        </div>
      </div>
    <% end %>
</div>

app/views/autorizations/authorizations_administration.html.erb
<% provide(:title, 'additional_hours') %>

<div class="content">

    <!-- Start Content-->
    <div class="container-fluid">
        
        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="<%= root_path %>">Accueil</a></li>
                            <li class="breadcrumb-item active">Autorisations</li>
                        </ol>
                    </div>
                    <h4 class="page-title">Mes autorisations</h4>
                </div>
            </div>
        </div>     
        <!-- end page title --> 

        <div class="row">
            <div class="col-sm-12">
                <div class="card-box">
                  <div class="bg-light d-flex justify-content-between mb-2">
                    <div class="text-sm-center form-inline">
                      <%= link_to '#new_authorization_administration', class: "btn btn-primary", :id => 'login', "data-toggle" => "modal", 'data-target' => '#new_authorization_administration'  do %>
                        <i class="mdi mdi-plus mr-1">Demmande d'autorisations</i>
                      <% end %>
                      <div class="form-group ml-2">
                        <input id="demo-input-search2" type="text" placeholder="Search" class="form-control" autocomplete="off">
                      </div>
                    </div>

                    <div class="text-sm-center d-flex">
                      <h5 class="text-muted text-sm mr-1 text-truncate">Votre solde des heures sup des jours fériés: <span data-plugin="counterup"><%= @balance_open_additional_hour_off_days %></span></h5>
                      <div class="btn-group dropright">
                        <button type="button" class="btn btn-secondary" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Filtrer par status
                        </button>
                        <div class="dropdown-menu" style="">
                          <a class="dropdown-item" href="<%#= additional_hours_administration_path() %>"><i class="mdi mdi-checkbox-blank-circle-outline mr-1 text-green"></i>Tous</a>
                          <a class="dropdown-item" href="<%#= additional_hours_administration_path(additional_hour_type: 'HSJO') %>"><i class="mdi mdi-checkbox-blank-circle-outline mr-1 text-green"></i>HSJO</a>
                          <a class="dropdown-item" href="<%#= additional_hours_administration_path(additional_hour_type: 'HSJFT') %>"><i class="mdi mdi-checkbox-blank-circle-outline mr-1 text-danger"></i>HSJFT</a>
                        </div>
                      </div>
                    </div>

                  </div>
                  <table id="demo-foo-addrow" class="table table-centered table-striped table-bordered mb-0 toggle-circle" data-page-size="7">
                    <thead>
                    <tr>
                      <% if ['Super Admin', 'Rh'].include? current_user.role.title %>
                        <th data-sort-initial="true" data-toggle="true">Collaborateurs</th>
                      <% end %>
                      <th>Date de sortie</th>
                      <th data-hide="phone, tablet">Heure de début</th>
                      <th data-hide="phone, tablet">Heure de fin</th>
                      <th data-hide="phone, tablet">Statut</th>

                      <th data-hide="phone, tablet">Actions</th>

                    </tr>
                    </thead>
                    <tbody>
                    <% @autorizations.each do |autorization| %>
                      <tr>
                        <% if ['Super Admin', 'Rh'].include? current_user.role.title %>
                          <td><%= "#{autorization.user.last_name} #{autorization.user.first_name}" %></td>
                        <% end %>
                        <td><%= autorization.date %></td>
                        <td><%= autorization.start_hour %></td>
                        <td><%= autorization.end_hour %></td>
                        <td>
                          <% if autorization.created? %>
                            <div class="badge font-14 badge badge-info p-1">Enregisté</div>
                          <% elsif autorization.soumis? %>
                            <div class="badge font-14 badge badge-warning p-1">Soumis</div>
                          <% elsif autorization.aprouved? %>
                            <div class="badge font-14 badge badge-success p-1">Validé</div>
                          <% elsif autorization.encours? %>
                            <div class="badge font-14 badge badge-pink p-1">En cours</div>
                          <% end %>
                        </td>
                        <td>
                          <%= link_to autorization_path(autorization), remote: true, class: "action-icon" do %>
                            <i class="mdi mdi-eye"></i>
                          <% end %>

                          <% if autorization.created? %>
                            <%= link_to edit_autorization_path(autorization), remote: true, class: "action-icon" do %>
                              <i class="mdi mdi-border-color"></i>
                            <% end %>

                            <%= link_to soumettre_autorization_path(autorization), data: { confirm: 'Etes vous sur?',  title: 'Confirme la soumission?' }, title: "Soumettre", class: "action-icon" do %>
                              <i class="mdi mdi-checkbox-multiple-marked-circle-outline"></i>
                            <% end %>

                            <%= link_to autorization, method: :delete, data: { confirm: 'Etes vous sur?', title: 'Confirme la suppression?' }, title: "Suprimer", class: "action-icon" do %>
                              <i class="mdi mdi-delete"></i>
                            <% end %>
                          <% elsif autorization.aprouved? %>
                              <%= link_to to_print_authorisation_path(autorization, format: 'pdf'), title: "Imprimer", class: "action-icon" do %>
                                  <i class="mdi mdi-printer"></i>
                              <% end %>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                    </tbody>
                    <tfoot>
                    <tr class="active">
                      <td colspan="8">
                        <div class="text-right">
                          <ul class="pagination pagination-split justify-content-end footable-pagination m-t-10"></ul>
                        </div>
                      </td>
                    </tr>
                    </tfoot>
                  </table>
                </div> <!-- end card-->
            </div> <!-- end col -->
        </div>
    </div>
    <!-- end row -->

    <footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    &copy; Copyright Alithya - <script>document.write(new Date().getFullYear())</script> 
                </div>
            </div>
        </div>
    </footer> 
    <div id='remote-container'></div>
</div> <!-- content -->

<!--  Modal content for the Large example -->
<div class="modal fade" id="new_authorization_administration" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myLargeModalLabel">Demande d'autorisation</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <%= simple_form_for(Autorization.new, as: :autorization, method: :post, url: create_for_him_self_path, html: { class: "form-horizontal" }) do |f| %>
                
                <div class="modal-body">

                    <%= f.input :user_id, label: false, input_html: { id: 'user_id', value: current_user.id, :style => "display:none;" } %>
                    
                    <div class="col-12">
                        <%= f.input :department, label: 'Département', class: 'form-control' %>
                    </div>

                    <div class="col-12">
                        <%= f.input :function, label: 'Fonction', class: 'form-control' %>
                    </div>
                    
                    <div class="form-group mb-3">
                        <div class="row">
                            <div class="col-12">
                                <%= f.input :date, label: 'Date de sortie', as: :date ,html5: true, placeholder: "Entrer la date de début d'autorisation", class: 'form-control', input_html: { id: 'date', onchange:'reloadHourDuration();' } %>
                            </div>
                       </div>
                   </div>
 
                    <div class="form-group mb-3">
                        <div class="row">
                            <div class="col-8">
                                 <%= f.input :start_hour, label: 'Heure de début', as: :select, collection: (['8:00','9:00','10:00','11:00','12:00','14:00','15:00','16:00','17:00','18:00']), :selected => '8:00', html5: true, placeholder: "Entrer l'heur de début", input_html: { id: 'hour_start', onchange:'reloadHourDuration();' }, class: 'form-control' %>
                            </div>
                            <div class="col-4">
                                <%= f.input :end_hour, label: 'Heure de reprise', as: :select, collection: (['8:00','9:00','10:00','11:00','12:00','14:00','15:00','16:00','17:00','18:00']), :selected => '8:00', html5: true, placeholder: "Entrer l'heur de fin", input_html: { id: 'hour_end', onchange:'reloadHourDuration();' }, class: 'form-control' %>
                            </div>
                            <div class="col-12">
                                <h4><span class="badge badge-danger ml-1" id="dr"></span></h4>
                            </div>
                            <div class="col-12">
                               <h4><span class="badge badge-danger ml-1 valid_hours"></span></h4>
                            </div>
                            <div class="col-12" id="recovery_method" style="display:none;">
                                <%= f.input :recovery_method, as: :radio_buttons, label: 'Méthode de récuperation', collection: [['0', 'Répartition des heures sur les autres jours travaillés de la semaine'], ['1', 'Retrancher de mon solde de congé']], label_method: :second, value_method: :first %>  
                            </div>
                            <div class="col-12">
                                <%= f.input :comment, label: 'Motif', class: 'form-control' %>
                            </div>
                        </div>
                    </div>
                                       
                </div>

                <div class="modal-footer">
                    <div id="submit_button">
                       <%= f.button :submit, 'Confirmer', class: 'btn btn-raised btn-success' %>
                    </div> 
                    <button type="button" class="btn btn-raised btn-warning" data-dismiss="modal">Annuler</button>
                </div>
            <% end %>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal --> 

<script>
    function set_user_id(){

        var user_name = document.getElementsByClassName("select2")[0].innerText;

        console.log(user_name);

        var url = '<%= domainename + 'finduserid/' %>';
        $.when(
            $.getJSON(url+user_name)
        ).done( function(json) {

            $('#user_id').val(json);
              
        }); 

    }

    function reloadHourDuration() {
        var date = document.getElementById("date").value;
        var start_hour = document.getElementById("hour_start").value;
        var end_hour = document.getElementById("hour_end").value;
        var user_id = document.getElementById("user_id").value;
        var url = '<%= domainename + 'authorization_hour_taken/' %>';

        console.log("user_id" + user_id);
        $.when(
            $.getJSON(url+user_id+'/'+date+'/'+start_hour+'/'+end_hour)
        ).done( function(json) {

            if(json.authorization__hour_duration > 0 && json.authorization__hour_duration <= 4) {
                    $('#dr').text(json.authorization__hour_duration + " heure(s) dans cette autorisation");
                    document.getElementById("submit_button").style.display = "block"; 
                     if(json.count_authorizations >= 4){
                        $('.valid_hours').text("Dépassement des 4 autorisations possible en mois courant");
                         document.getElementById("submit_button").style.display = "none"; 
                     }
            }
            if(json.authorization__hour_duration > 4){
                $('#dr').text("Vous avez dépassé les 4 heures");
                document.getElementById("submit_button").style.display = "none";
            }
            if(json.authorization__hour_duration == 0){
                $('#dr').text("0 heures");
                document.getElementById("submit_button").style.display = "none";
            }

            if(json.authorization__hour_duration >= 3 && json.authorization__hour_duration <= 4) {
                document.getElementById("recovery_method").style.display = "block";
            }else{
                document.getElementById("recovery_method").style.display = "none";
            }

        }); 

    }

</script>

app/views/autorizations/edit.js.erb
$('#remote-container').html('<%= j render "autorizations/form" %>');
$('#edit_autorization').modal('show');

app/views/autorizations/pre_export_authorizations.js.erb
$('#remote-container').html('<%= j render "autorizations/pre_export_authorizations" %>');
$('#export_autorization').modal('show');

app/views/autorizations/pre_recovered.js.erb
$('#remote-container').html('<%= j render "autorizations/pre_recovered" %>');
$('#recovered_autorization').modal('show');

app/views/autorizations/pre_refus.js.erb
$('#remote-container').html('<%= j render "autorizations/pre_refus" %>');
$('#refus_autorization').modal('show');

app/views/autorizations/show.js.erb
$('#remote-container').html('<%= j render "autorizations/show" %>');
$('#show_autorization').modal('show');