config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq", as: :sidekiq

  resources :users, only: [:create, :update] do
    collection { post :import }
  end
  devise_scope :user do
    devise_for :users, :controllers => {:registrations => "my_devise/registrations"}
    resources :users, except: [:create, :update]

    
    get "/users/sign_up",  :to => 'welcomes#index'
   
    authenticated :user do
      root 'welcomes#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end   
  end

  get 'enable/:id' => 'users#enable', as: 'enable'
  get 'disable/:id' => 'users#pre_disable', as: 'pre_disable'
  post 'disable/:id' => 'users#disable', as: 'disable'
  get '/users/role/:title', to: 'users#users_by_role', as: :users_by_role

  resources :companies

  root 'welcomes#index'

  get '/export' => 'welcomes#export', as: 'export'
  get '/en-cours-developement' => 'welcomes#en_cours_devlopement', as: 'en_cours_devlopement'

  get '/start_load' =>  'load_updated_files#start_load', as: 'start_load'

  resources :fonctional_manager_externs do
    collection { post :import }
  end

  resources :furloughs
  get 'validate/:id' => 'furloughs#validate', as: 'validate'
  get 'approuve/:id' => 'furloughs#valide_fc', as: 'valide_fc'
  get 'in_progress/:id' => 'furloughs#in_progress', as: 'in_progress'
  get 'soumettre/:id' => 'furloughs#soumettre', as: 'soumettre'
  get 'mes-congés' => 'furloughs#furloughs_administration', as: 'furloughs_administration'
  get 'congé/:id' => 'furloughs#show_administration', as: 'show_administration'
  get 'refuse/:id' => 'furloughs#pre_refuse', as: 'pre_refuse'
  post 'refuse/:id' => 'furloughs#refuse', as: 'refuse'
  get 'cancel/:id' => 'furloughs#pre_cancel', as: 'pre_cancel'
  post 'cancel/:id' => 'furloughs#cancel', as: 'cancel'
  get 'print/:id' => 'furloughs#to_print', as: 'print'
  get 'findtypefurlough/:id' => 'furloughs#find_furlough_type', as: 'find_furlough_type'
  get 'getitemtohiligh/' => 'furloughs#get_item_to_hiligh', as: 'get_item_to_hiligh'
  get 'findfonctionalmanagerid/:name' => 'furloughs#find_fonctional_manager_id', as: 'find_fonctional_manager_id'
  get 'finduserid/:name' => 'furloughs#find_user_id', as: 'find_user_id'
  get 'findlinemanagerid/:name' => 'furloughs#find_line_manager_id', as: 'find_line_manager_id'
  get 'discontinuity/:id' => 'furloughs#pre_discontinuity', as: 'pre_discontinuity'
  post 'discontinuity/:id' => 'furloughs#discontinuity', as: 'discontinuity'
  get 'regularized/:id' => 'furloughs#pre_regularized', as: 'pre_regularized'
  post 'regularized/:id' => 'furloughs#regularized', as: 'regularized'
  get 'stop/:id' => 'furloughs#pre_stop', as: 'pre_stop'
  post 'stop/:id' => 'furloughs#stop', as: 'stop'
  get 'duration_hour_taken/:user_id/:start/:hour_start/:end/:hour_end' => 'furloughs#duration_hour_taken', as: 'duration_hour_taken'
  get 'duration_taken/:start/:hour_start/:end/:hour_end' => 'furloughs#durations_taken', as: 'duration_taken'

  resources :furlough_types do
    collection { post :import }
  end
  get 'enablefurloughtype/:id' => 'furlough_types#enable_furlough_type', as: 'enable_furlough_type'
  get 'disablefurloughtype/:id' => 'furlough_types#disable_furlough_type', as: 'disable_furlough_type'


  resources :offs do
    collection { post :import }
  end
  get 'adjust/:id' => 'offs#pre_adjust', as: 'pre_adjust'
  post 'adjust/:id' => 'offs#adjust', as: 'adjust'

  resources :additional_hours  
  get 'soumettreHeuresSup/:id' => 'additional_hours#soumettre_additional_hour', as: 'soumettre_additional_hour'
  get 'mes-heures-sup' => 'additional_hours#additional_hours_administration', as: 'additional_hours_administration'
  get 'period/:additional_hour_date' => 'additional_hours#get_period', as: 'get_period'
  get 'days_of_input_form/:period' => 'additional_hours#get_days_of_input_form', as: 'get_days_of_input_form'
  get 'valid_hours/:start/:hour_start/:end/:hour_end' => 'additional_hours#get_valid_hours', as: 'get_valid_hours'
  get 'export-heures-sup' => 'additional_hours#pre_export_additional_hours', as: 'pre_export_additional_hours'
  get 'export-heures-sup-lolo' => 'additional_hours#export_additional_hours', as: 'export_additional_hours'

  resources :autorizations 
  get 'soumettreAuthorization/:id' => 'autorizations#soumettre_autorization', as: 'soumettre_autorization'
  get 'mes-authorisations' => 'autorizations#authorizations_administration', as: 'authorizations_administration'
  get 'authorization_hour_taken/:user_id/:date/:start_hour/:end_hour' => 'autorizations#duration_hour_taken_of_authorization', as: 'duration_hour_taken_of_authorization'
  get 'export-authorizations' => 'autorizations#pre_export_authorizations', as: 'pre_export_authorizations'
  get 'export-authorizations-lolo' => 'autorizations#export_authorizations', as: 'export_authorizations'
  get 'recovered/:id' => 'autorizations#pre_recovered', as: 'pre_recovered'
  post 'recovered/:id' => 'autorizations#recovered', as: 'recovered'
  post 'create_for_a_collaborator' => 'autorizations#create_for_a_collaborator', as: 'create_for_a_collaborator'
  post 'create_for_himself' => 'autorizations#create_for_him_self', as: 'create_for_him_self'
  get 'printauthorisation/:id' => 'autorizations#to_print_authorisation', as: 'to_print_authorisation'
  get 'validateAuthorization/:id' => 'autorizations#validate_autorization', as: 'validate_autorization'
  get 'refuseAuthorization/:id' => 'autorizations#pre_refus', as: 'pre_refus'
  post 'refuseAuthorization/:id' => 'autorizations#refus_autorization', as: 'refus_autorization'

  resources :absence_types

  resources :absences
  get 'export-absences' => 'absences#pre_export_absences', as: 'pre_export_absences'
  get 'export-absences-lolo' => 'absences#export_absences', as: 'export_absences'

  resources :formation_types

  resources :formations

  resources :interns

  resources :certificate_requests
  get 'printAttestation/:id' => 'certificate_requests#to_print', as: 'print_attestation'
  get 'mes-demandes-attestations' => 'certificate_requests#certificate_requests_administration', as: 'certificate_requests_administration'
  get 'validate-attestation/:id' => 'certificate_requests#validate_certificate', as: 'validate_certificate'
  get 'certificate/:id' => 'certificate_requests#pre_certificate', as: 'pre_certificate'
  post 'certificate/:id' => 'certificate_requests#certificate', as: 'certificate'
  get 'refus-certificate/:id' => 'certificate_requests#pre_refus_certificate', as: 'pre_refus_certificate'
  post 'refuscertificate/:id' => 'certificate_requests#refus_certificate', as: 'refus_certificate'

  resources :projects
  get 'deleteproject/:id' => 'projects#delete_project', as: 'delete_c'
  get 'disableproject/:id' => 'projects#disable_project', as: 'disable_project'
  get 'enableproject/:id' => 'projects#enable_project', as: 'enable_project'
  get 'findprojectid/:name' => 'projects#find_project_id', as: 'find_project_id'
  get 'unarchiveproject/:id' => 'projects#unarchive_project', as: 'unarchive_project'

  resources :affectations
  get 'disaffectation/:id' => 'affectations#pre_disaffectation', as: 'pre_disaffectation'
  post 'disaffectation/:id' => 'affectations#disaffectation', as: 'disaffectation'
  get 'mes-affectations' => 'affectations#mes_affectations', as: 'mes_affectations'
  get 'disaffectation/:user_id/:project_id' => 'affectations#disaffectation_through_project', as: 'project_disaffectation'

  resources :costs
  get 'archivedcost' => 'costs#archived_cost', as: 'archived_cost'
  get 'disablecost/:id' => 'costs#disable_cost', as: 'disable_cost'
  get 'enablecost/:id' => 'costs#enable_cost', as: 'enable_cost'
  get 'findcostid/:name' => 'costs#find_cost_id', as: 'find_cost_id'
  get 'deletecost/:id' => 'costs#delete_cost', as: 'delete_cost'
  get 'unarchivecost/:id' => 'costs#unarchive_cost', as: 'unarchive_cost'
  get 'deleteproject/:id' => 'costs#delete_project', as: 'delete_project'

  resources :notes
  get 'mes-notes' => 'notes#mes_notes', as: 'mes_notes'
  get 'projects-by-user/:name' => 'notes#project_users', as: 'project_users'

  resources :stop_actions do
    collection { post :import }
  end

  resources :grounds do
    collection { post :import }
  end

  resources :user_confs
  
  resources :template_attestations

  resources :journals

  resources :settings
end

app/models/cost.rb
class Cost < ApplicationRecord
  validates :name, presence: true, format: {with: /[a-zA-Z]/}, uniqueness: true

  acts_as_tenant :company
  has_many :notes
  has_many :users, through: :notes

  scope :filter_by_status, -> (status) { where('costs.status = ?', status) }
  scope :filter_by_active, -> { where(is_active: true) }

  enum status: {
    created: 1,
    deleted: 2,
  }

end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show , :edit, :update, :destroy, :enable_cost, :disable_cost, :delete_cost, :unarchive_cost]

  def index
    @setting = Setting.find(1)
    if params[:status].present?
      @costs = Cost.filter_by_status(2)
    else
      @costs = Cost.filter_by_status(1)
    end
  end


  def show
  end

  def new
    @cost = Cost.new
  end

  def create
    @cost = Cost.new(cost_params)
    @cost.is_active = true
    @cost.enabled_date = Date.today
    if @cost.save
      redirect_to costs_path,  success: "Le coût est créé avec succès."
    else
      redirect_to costs_path, danger: "#{@cost.errors.full_messages}"
    end
  end

  def find_cost_id
    name = params[:name].split.first
    cost = Cost.find_by(name: name)
    render :json => cost.id
  end

  def edit
  end


  def update
     @cost = Cost.find(params[:id])
     if @cost.update(cost_params)
       redirect_to costs_path,  success: "Le Frais est édité avec succès"
     else
       redirect_to costs_path ,danger: "#{@cost.errors.full_messages}"
     end
  end

  def delete_cost
    @cost.is_active = false
    @cost.disabled_date = Date.today
    @cost.deleted!
    if @cost.save
      redirect_to costs_path, notice: "Le Frais est supprimé avec succès."
    else
      redirect_to costs_path ,danger: "#{@cost.errors.full_messages}"
    end
  end

  def unarchive_cost
    @cost.created!
    if @cost.save
      redirect_to costs_path, notice: "Le cout est désarchivé avec succès."
    end
  end

  def disable_cost
    @cost.is_active = false
    @cost.disabled_date = Date.today
    if @cost.save
      redirect_to costs_path, success: "Le Frais est désactivé avec succès"
    else
      redirect_to costs_path, danger: "#{@cost.errors.full_messages}"
    end
  end

  def enable_cost
    @cost.is_active = true
    @cost.enabled_date = Date.today
    if @cost.save
      redirect_to costs_path, success: "Le Frais est activé avec succès"
    else
      redirect_to costs_path, danger: "#{@cost.errors.full_messages}"
    end
  end


  private
    def set_cost
      @cost = Cost.find(params[:id])
    end

  def cost_params
    params.require(:cost).permit(:name, :percentage, :max_value)
  end
end

app/views/costs/index.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="page-title-box">
          <div class="page-title-right">
            <ol class="breadcrumb m-0">
              <li class="breadcrumb-item"><a href="<%= root_path %>">Accueil</a></li>
              <li class="breadcrumb-item active">Actions</li>
            </ol>
          </div>
          <h4 class="page-title">Liste des Categories</h4>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <div class="card-box">
          <div class="bg-light d-flex justify-content-between mb-2">
            <div class="text-sm-center form-inline">
              <div class="form-group mr-2">
                <% if ['Super Admin', 'Rh'].include? current_user.role.title %>
                  <%= link_to '#new_cost', class: "btn btn-primary", :id => 'login', "data-toggle" => "modal", 'data-target' => '#new_cost'  do %>
                    <i class="mdi mdi-plus mr-1"> Nouveau Type des Frais</i>
                  <% end %>
                <% end %>
              </div>
              <div class="form-group mr-2">
                <input id="demo-input-search2" type="text" placeholder="Search" class="form-control" autocomplete="off">
              </div>
            </div>
            <% if ['Super Admin', 'Rh'].include? current_user.role.title %>
              <div class="d-flex justify-content-end align-items-center">
                <% if  params.has_key?(:status)%>
                  <a class="btn btn-secondary" href="<%= costs_path %>"> <i class="mdi mdi-filter"></i> Categories</a>
                <% else %>
                  <a class="btn btn-secondary" href="<%= costs_path(status: 'deleted') %>"> <i class="mdi mdi-filter"></i>Categories Archivé</a>
                <% end %>
              </div>
            <% end %>
          </div>
          <table id="demo-foo-addrow" class="table table-centered table-striped table-bordered mb-0 toggle-circle" data-page-size="7">
            <thead>
            <tr>
              <th data-sort-initial="true" data-toggle="true">Nom</th>
              <th data-hide="phone, tablet">Percentage</th>
              <th data-hide="phone, tablet">Coût maximum</th>
              <th data-hide="phone, tablet">Status</th>
              <th data-hide="phone, tablet">Actions</th>
            </tr>
            </thead>
            <tbody>
            <% @costs.each do |cost| %>
              <tr>
                <td> <%= cost.name %> </td>
                <td> <% if cost.percentage %>
                    <%= cost.percentage %>%
                  <% else %>
                    NaN
                  <% end %></td>
                <td> <% if cost.max_value %>
                    <%= cost.max_value %>  Dh
                  <% else %>
                    NaN
                  <% end %></td>
                <td>
                  <% if cost.is_active %>
                    <span class="badge badge-success">Actif</span>
                  <% else %>
                    <span class="badge badge-dark">Désactiver</span>
                  <% end %>
                </td>
                <td class="action">
                  <%= link_to cost_path(cost), remote: true, class: "action-icon" do %>
                    <i class="mdi mdi-eye"></i>
                  <% end %>

                  <%= link_to  edit_cost_path(cost), remote: true, class: "action-icon" do %>
                    <i class="mdi mdi-border-color"></i>
                  <% end %>

                  <% if cost.status != 'deleted' %>
                    <%= link_to delete_cost_path(cost.id), data: { confirm: 'Etes vous sur?', title: 'Confirme la suppression?' }, title: "Suprimer", class: "action-icon" do %>
                      <i class="mdi mdi-archive-arrow-down"></i>
                    <% end %>
                  <% else %>
                    <%= link_to unarchive_cost_path(cost.id), data: { confirm: 'Etes vous sur?', title: 'Confirme le désarchivage?' }, title: "Suprimer", class: "action-icon" do %>
                      <i class="mdi mdi-archive-arrow-up"></i>
                    <% end %>
                  <% end %>

                  <% if cost.is_active == true %>
                    <%= link_to disable_cost_path(cost), data: { confirm: 'Etes vous sur de disativer?', title: 'Confirme le changement du status?' }, title: "changement du status", class: "action-icon" do %>
                      <i class="mdi mdi-lock"></i>
                    <% end %>
                  <% else %>
                    <%= link_to enable_cost_path(cost), data: { confirm: 'Etes vous sur d activer?', title: 'Confirme le changement du status?' }, title: "changement du status", class: "action-icon" do %>
                      <i class="mdi mdi-lock-open"></i>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
            </tbody>
            <tfoot>
            <tr class="active">
              <td colspan="8">
                <div class="text-right">
                  <ul class="pagination pagination-split justify-content-end footable-pagination m-t-10"></ul>
                </div>
              </td>
            </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
    <div id='remote-container'></div>
</div>


<div class="modal fade" id="new_cost" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myLargeModalLabel">Ajout des Categories</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      </div>
      <%= simple_form_for(Cost.new, as: :cost, method: :post, html: { class: "form-horizontal" }) do |f| %>
        <div class="modal-body">
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="form-group">
            <%= f.input :name, label: 'Name', placeholder: "Entrer le nom", class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :percentage %>
            <%= f.select :percentage, [['25%',25],['50%',50],['75%',75],['100%',100]] , {include_blank: true }, { :class => 'form-control' }%>
          </div>

          <div class="form-group">
            <%= f.input :max_value, label: 'Coût maximum', placeholder: "Entrer le coût maximum", class: 'form-control' %>
          </div>

        </div>

        <div class="modal-footer d-flex justify-content-between">
          <div>
            <%= f.button :submit, 'Ajouter', class: 'btn btn-raised btn-success' %>
          </div>
          <button type="button" class="btn btn-raised btn-warning" data-dismiss="modal">Annuler</button>
        </div>

      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div>
</div><!-- /.modal -->