config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq", as: :sidekiq

  resources :users, only: [:create, :update] do
    collection { post :import }
  end
  devise_scope :user do
    devise_for :users, :controllers => {:registrations => "my_devise/registrations"}
    resources :users, except: [:create, :update]

    
    get "/users/sign_up",  :to => 'welcomes#index'
   
    authenticated :user do
      root 'welcomes#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end   
  end

  get 'enable/:id' => 'users#enable', as: 'enable'
  get 'disable/:id' => 'users#pre_disable', as: 'pre_disable'
  post 'disable/:id' => 'users#disable', as: 'disable'
  get '/users/role/:title', to: 'users#users_by_role', as: :users_by_role

  resources :companies

  root 'welcomes#index'

  get '/export' => 'welcomes#export', as: 'export'
  get '/en-cours-developement' => 'welcomes#en_cours_devlopement', as: 'en_cours_devlopement'

  get '/start_load' =>  'load_updated_files#start_load', as: 'start_load'

  resources :fonctional_manager_externs do
    collection { post :import }
  end

  resources :furloughs
  get 'validate/:id' => 'furloughs#validate', as: 'validate'
  get 'approuve/:id' => 'furloughs#valide_fc', as: 'valide_fc'
  get 'in_progress/:id' => 'furloughs#in_progress', as: 'in_progress'
  get 'soumettre/:id' => 'furloughs#soumettre', as: 'soumettre'
  get 'mes-congés' => 'furloughs#furloughs_administration', as: 'furloughs_administration'
  get 'congé/:id' => 'furloughs#show_administration', as: 'show_administration'
  get 'refuse/:id' => 'furloughs#pre_refuse', as: 'pre_refuse'
  post 'refuse/:id' => 'furloughs#refuse', as: 'refuse'
  get 'cancel/:id' => 'furloughs#pre_cancel', as: 'pre_cancel'
  post 'cancel/:id' => 'furloughs#cancel', as: 'cancel'
  get 'print/:id' => 'furloughs#to_print', as: 'print'
  get 'findtypefurlough/:id' => 'furloughs#find_furlough_type', as: 'find_furlough_type'
  get 'getitemtohiligh/' => 'furloughs#get_item_to_hiligh', as: 'get_item_to_hiligh'
  get 'findfonctionalmanagerid/:name' => 'furloughs#find_fonctional_manager_id', as: 'find_fonctional_manager_id'
  get 'finduserid/:name' => 'furloughs#find_user_id', as: 'find_user_id'
  get 'findlinemanagerid/:name' => 'furloughs#find_line_manager_id', as: 'find_line_manager_id'
  get 'discontinuity/:id' => 'furloughs#pre_discontinuity', as: 'pre_discontinuity'
  post 'discontinuity/:id' => 'furloughs#discontinuity', as: 'discontinuity'
  get 'regularized/:id' => 'furloughs#pre_regularized', as: 'pre_regularized'
  post 'regularized/:id' => 'furloughs#regularized', as: 'regularized'
  get 'stop/:id' => 'furloughs#pre_stop', as: 'pre_stop'
  post 'stop/:id' => 'furloughs#stop', as: 'stop'
  get 'duration_hour_taken/:user_id/:start/:hour_start/:end/:hour_end' => 'furloughs#duration_hour_taken', as: 'duration_hour_taken'
  get 'duration_taken/:start/:hour_start/:end/:hour_end' => 'furloughs#durations_taken', as: 'duration_taken'

  resources :furlough_types do
    collection { post :import }
  end
  get 'enablefurloughtype/:id' => 'furlough_types#enable_furlough_type', as: 'enable_furlough_type'
  get 'disablefurloughtype/:id' => 'furlough_types#disable_furlough_type', as: 'disable_furlough_type'


  resources :offs do
    collection { post :import }
  end
  get 'adjust/:id' => 'offs#pre_adjust', as: 'pre_adjust'
  post 'adjust/:id' => 'offs#adjust', as: 'adjust'

  resources :additional_hours  
  get 'soumettreHeuresSup/:id' => 'additional_hours#soumettre_additional_hour', as: 'soumettre_additional_hour'
  get 'mes-heures-sup' => 'additional_hours#additional_hours_administration', as: 'additional_hours_administration'
  get 'period/:additional_hour_date' => 'additional_hours#get_period', as: 'get_period'
  get 'days_of_input_form/:period' => 'additional_hours#get_days_of_input_form', as: 'get_days_of_input_form'
  get 'valid_hours/:start/:hour_start/:end/:hour_end' => 'additional_hours#get_valid_hours', as: 'get_valid_hours'
  get 'export-heures-sup' => 'additional_hours#pre_export_additional_hours', as: 'pre_export_additional_hours'
  get 'export-heures-sup-lolo' => 'additional_hours#export_additional_hours', as: 'export_additional_hours'

  resources :autorizations 
  get 'soumettreAuthorization/:id' => 'autorizations#soumettre_autorization', as: 'soumettre_autorization'
  get 'mes-authorisations' => 'autorizations#authorizations_administration', as: 'authorizations_administration'
  get 'authorization_hour_taken/:user_id/:date/:start_hour/:end_hour' => 'autorizations#duration_hour_taken_of_authorization', as: 'duration_hour_taken_of_authorization'
  get 'export-authorizations' => 'autorizations#pre_export_authorizations', as: 'pre_export_authorizations'
  get 'export-authorizations-lolo' => 'autorizations#export_authorizations', as: 'export_authorizations'
  get 'recovered/:id' => 'autorizations#pre_recovered', as: 'pre_recovered'
  post 'recovered/:id' => 'autorizations#recovered', as: 'recovered'
  post 'create_for_a_collaborator' => 'autorizations#create_for_a_collaborator', as: 'create_for_a_collaborator'
  post 'create_for_himself' => 'autorizations#create_for_him_self', as: 'create_for_him_self'
  get 'printauthorisation/:id' => 'autorizations#to_print_authorisation', as: 'to_print_authorisation'
  get 'validateAuthorization/:id' => 'autorizations#validate_autorization', as: 'validate_autorization'
  get 'refuseAuthorization/:id' => 'autorizations#pre_refus', as: 'pre_refus'
  post 'refuseAuthorization/:id' => 'autorizations#refus_autorization', as: 'refus_autorization'

  resources :absence_types

  resources :absences
  get 'export-absences' => 'absences#pre_export_absences', as: 'pre_export_absences'
  get 'export-absences-lolo' => 'absences#export_absences', as: 'export_absences'

  resources :formation_types

  resources :formations

  resources :interns

  resources :certificate_requests
  get 'printAttestation/:id' => 'certificate_requests#to_print', as: 'print_attestation'
  get 'mes-demandes-attestations' => 'certificate_requests#certificate_requests_administration', as: 'certificate_requests_administration'
  get 'validate-attestation/:id' => 'certificate_requests#validate_certificate', as: 'validate_certificate'
  get 'certificate/:id' => 'certificate_requests#pre_certificate', as: 'pre_certificate'
  post 'certificate/:id' => 'certificate_requests#certificate', as: 'certificate'
  get 'refus-certificate/:id' => 'certificate_requests#pre_refus_certificate', as: 'pre_refus_certificate'
  post 'refuscertificate/:id' => 'certificate_requests#refus_certificate', as: 'refus_certificate'

  resources :projects
  get 'deleteproject/:id' => 'projects#delete_project', as: 'delete_c'
  get 'disableproject/:id' => 'projects#disable_project', as: 'disable_project'
  get 'enableproject/:id' => 'projects#enable_project', as: 'enable_project'
  get 'findprojectid/:name' => 'projects#find_project_id', as: 'find_project_id'
  get 'unarchiveproject/:id' => 'projects#unarchive_project', as: 'unarchive_project'

  resources :affectations
  get 'disaffectation/:id' => 'affectations#pre_disaffectation', as: 'pre_disaffectation'
  post 'disaffectation/:id' => 'affectations#disaffectation', as: 'disaffectation'
  get 'mes-affectations' => 'affectations#mes_affectations', as: 'mes_affectations'
  get 'disaffectation/:user_id/:project_id' => 'affectations#disaffectation_through_project', as: 'project_disaffectation'

  resources :costs
  get 'archivedcost' => 'costs#archived_cost', as: 'archived_cost'
  get 'disablecost/:id' => 'costs#disable_cost', as: 'disable_cost'
  get 'enablecost/:id' => 'costs#enable_cost', as: 'enable_cost'
  get 'findcostid/:name' => 'costs#find_cost_id', as: 'find_cost_id'
  get 'deletecost/:id' => 'costs#delete_cost', as: 'delete_cost'
  get 'unarchivecost/:id' => 'costs#unarchive_cost', as: 'unarchive_cost'
  get 'deleteproject/:id' => 'costs#delete_project', as: 'delete_project'

  resources :notes
  get 'mes-notes' => 'notes#mes_notes', as: 'mes_notes'
  get 'projects-by-user/:name' => 'notes#project_users', as: 'project_users'

  resources :stop_actions do
    collection { post :import }
  end

  resources :grounds do
    collection { post :import }
  end

  resources :user_confs
  
  resources :template_attestations

  resources :journals

  resources :settings
end

app/models/intern.rb
class Intern < ApplicationRecord
    
    serialize :technical_skills, Array
    serialize :language_skills, Array

    validates :matricule, presence: true
    validates :matricule, uniqueness: true

    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :email, uniqueness: true

    validates :gsm, presence: true
    validates :gsm, uniqueness: true

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :technical_skills, presence: true
    validates :language_skills, presence: true
    validates :college_year, presence: true

    acts_as_tenant :company

    LANGUAGES = ["Français", "Anglais"]
    SKILLS = ["Ruby On Rails", "Blender"]
end

app/controllers/interns_controller.rb
class InternsController < ApplicationController
  before_action :set_intern, only: %i[ show edit update destroy ]

  # GET /interns or /interns.json
  def index
    @interns = Intern.all
    @setting = Setting.find(1)
  end

  # GET /interns/1 or /interns/1.json
  def show
  end

  # GET /interns/new
  def new
    @intern = Intern.new
  end

  # GET /interns/1/edit
  def edit
  end

  # POST /interns or /interns.json
  def create
    @intern = Intern.new(intern_params)
    @intern.technical_skills = params[:technical_skills].split(",")

    respond_to do |format|
      if @intern.save
        format.html { redirect_to interns_url, notice: "Intern was successfully created." }
      else
        format.html { redirect_to interns_url, status: :unprocessable_entity }
      end
    end
  end

  def pre_export_additional_hours
    @additional_hours_periods = AdditionalHour.all.pluck(:period).uniq
  end

  def export_additional_hours
    @additional_hours = AdditionalHour.where(nil)
    @additional_hours = AdditionalHour.exported_data_filtred(@additional_hours, params)
    filename = "Rapport-heures-sup-" + Date.today.to_s + ".xlsx"

    respond_to do |format|
      format.xlsx { headers["Content-Disposition"] = "attachment; filename=\"#{filename}\"" }
    end
  end

  # PATCH/PUT /interns/1 or /interns/1.json
  def update
    respond_to do |format|
      if @intern.update(intern_params)
        format.html { redirect_to interns_url, notice: "Intern was successfully updated." }
      else
        format.html { redirect_to interns_url, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interns/1 or /interns/1.json
  def destroy
    @intern.destroy

    respond_to do |format|
      format.html { redirect_to interns_url, notice: "Intern was successfully destroyed." }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_intern
    @intern = Intern.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def intern_params
    params.require(:intern).permit(:matricule, :first_name, :last_name, :email, :gsm, :college_year, :past_interview, :opinion_interview, :is_passable, :desired_internship, :potential_internship, :opinion_internship, language_skills: [])
  end

end

app/views/interns/_pre_export_interns.html.erb
<!-- Modal -->
<div class="modal fade" id="export_absence" role="dialog">
    <%= form_tag export_absences_path(format: :xlsx), :method => 'get' do %>
      <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                 <h4 class="modal-title" id="myLargeModalLabel">Filtre du rapport</h4>
                 <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-6">
                        <%= label_tag "Date d'absence" %>
                        <%= date_field_tag :date_absence, "#{Date.today}", class:"form-control" %>
                    </div>
                    <div class="col-6">
                        <%= label_tag 'Opérateur Date' %>
                        <%= select_tag :opperateur_date, options_for_select(['Égale', 'Supérieure que', 'Supérieure ou égale','Inférieure que', 'Inférieure ou égale']), class:"form-control" %>
                    </div> 
                </div>
                <br>
                <div class="row">
                    <div class="col-12">
                        <%= label_tag "Type d'absences" %>
                        <%= select_tag :type_absences, options_for_select(['Tous', 'Absence Justifiée', 'Absence Injustifiée', 'Accident de travail']), class:"form-control" %>
                    </div> 
                </div>
                 <br>
                <div class="row">
                    <div class="col-12">
                        <%= label_tag "Type d'absences" %>
                        <%= select_tag :collaborateurs, options_for_select(["Tous"].concat(User.where.not(role_id: 1).pluck(:email))), class:"form-control" %>
                    </div> 
                </div>
            </div>
            
            <div class="modal-footer">
                <button type="submit" class="btn btn-raised btn-success"> Rapport</button>
            </div>
        </div>
      </div>
    <% end %>
</div>
 

app/views/interns/index.html.erb
<div class="content">

  <!-- Start Content-->
  <div class="container-fluid">

    <!-- start page title -->
    <div class="row">
      <div class="col-12">
        <div class="page-title-box">
          <div class="page-title-right">
            <ol class="breadcrumb m-0">
              <li class="breadcrumb-item"><a href="<%= root_path %>">Accueil</a></li>
              <li class="breadcrumb-item active">Stagiaires</li>
            </ol>
          </div>
          <h4 class="page-title">Liste des stagiaires</h4>
        </div>
      </div>
    </div>
    <!-- end page title -->

    <div class="row">
      <div class="col-sm-12">
        <div class="card-box">
          <div class="mb-2">
            <div class="bg-light d-flex justify-content-between">
              <div class="text-sm-center form-inline">
                <div class="form-group mr-2">
                  <%= link_to '#new_intern', class: "btn btn-primary", :id => 'login', "data-toggle" => "modal", 'data-target' => '#new_intern' do %>
                    <i class="mdi mdi-plus mr-1"> Nouveau stagiaire</i>
                  <% end %>
                </div>
                <div class="form-group">
                  <input id="demo-input-search2" type="text" placeholder="Search" class="form-control" autocomplete="off">
                </div>
              </div>
            </div>
          </div>

          <table id="demo-foo-addrow" class="table table-centered table-striped table-bordered mb-0 toggle-circle" data-page-size="7">
            <thead>
            <tr>
              <th data-sort-initial="true" data-toggle="true">Nom</th>
              <th>Prénom</th>
              <th data-hide="phone, tablet">Année universitaire</th>
              <th data-hide="phone, tablet">gsm</th>
              <th data-hide="phone, tablet">Entretien passé</th>
              <th data-hide="phone, tablet">Compétences Techniques</th>
              <th data-hide="phone, tablet">Compétences Linguistiques</th>

              <th data-hide="phone, tablet">Actions</th>
            </tr>
            </thead>
            <tbody>
            <% @interns.each do |intern| %>
              <tr>
                <td><%= intern.last_name %></td>
                <td><%= intern.first_name %></td>
                <td><%= intern.college_year %></td>
                <td><%= intern.gsm %></td>
                <% if intern.past_interview == true %>
                  <td><span class="badge label-table badge-success">Entretien passé</span></td>
                <% else %>
                  <td><span class="badge label-table badge-danger">Pas encore</span></td>
                <% end %>
                <td>
                  <% intern.technical_skills.each do |skill| %>
                    <span class="badge label-table badge-warning"><%= skill %></span>
                    <br>
                  <% end %>
                </td>
                <td>
                  <% intern.language_skills.each do |language| %>
                    <span class="badge label-table badge-danger"><%= language %></span>
                    <br>
                  <% end %>
                </td>
                <td>
                  <%= link_to intern_path(intern), remote: true, title: "Voir", class: "action-icon" do %>
                    <i class="mdi mdi-eye"></i>
                  <% end %>
                  <%= link_to edit_intern_path(intern), remote: true, title: "Modifier", class: "action-icon" do %>
                    <i class="mdi mdi-border-color"></i>
                  <% end %>
                  <%= link_to intern, method: :delete, data: { confirm: 'Etes vous sur?' }, title: "Suprimer", class: "action-icon" do %>
                    <i class="mdi mdi-delete"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
            </tbody>
            <tfoot>
            <tr class="active">
              <td colspan="8">
                <%= link_to pre_export_additional_hours_path(), remote: true, class: "btn btn-warning" do %>
                  Rapport des Stagiaires
                <% end %>
                <div class="text-right">
                  <ul class="pagination pagination-split justify-content-end footable-pagination m-t-10"></ul>
                </div>
              </td>
            </tr>
            </tfoot>
          </table>
        </div> <!-- end card-box -->
      </div> <!-- end col -->
    </div>
    <!-- end row -->
  </div>
</div> <!-- content -->

<!--  Modal content for the Large example -->
<div class="modal fade" id="new_intern" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myLargeModalLabel">Nouveau Stagiaire</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      </div>
      <%= simple_form_for(Intern.new, as: :intern, method: :post, html: { class: "form-horizontal" }) do |f| %>

        <div class="modal-body">
          <div class="form-group mb-3">
            <%= f.input :matricule, label: "Matricule", required: true, hint: "Le matricule doit être renseignè", class: 'form-control' %>
          </div>
          <div class="form-group mb-3">
            <%= f.input :first_name, label: "Prénom", required: true, hint: "Le prénom doit être renseignè", class: 'form-control' %>
          </div>
          <div class="form-group mb-3">
            <%= f.input :last_name, label: "Nom", required: true, hint: "Le nom doit être renseignè", class: 'form-control' %>
          </div>
          <div class="form-group mb-3">
            <%= f.input :email, label: "Email", required: true, hint: "L'eamil doit être renseignè", class: 'form-control' %>
          </div>
          <div class="form-group mb-3">
            <%= f.input :gsm, label: "Gsm", required: true, hint: "Le téléphone doit être renseignè", class: 'form-control' %>
          </div>
          <div class="form-group mb-3">
            <%= f.input :college_year, label: "Année univesitaire", required: true, hint: "L'année univesitaire doit être renseignè", class: 'form-control' %>
          </div>
          <div class="form-group mb-3">
            <label>Compétences Techniques</label>
            <input type="text" id="selectize-tags" name="technical_skills" value="" tabindex="-1" class="selectized" style="display: none;">
          </div>
          <div class="form-group mb-3">
            <label>Compétences Linguistiques</label> <br>
            <% Intern::LANGUAGES.each do |key| %>
              <%= f.check_box :language_skills, { multiple: true }, key, nil %>
              <%= f.label key %>
            <% end %>
          </div>
          <div class="form-group mb-3">
            <%= f.input :past_interview, label: "Entretien passé", as: :boolean, class: 'form-control' %>
          </div>
          <div class="form-group mb-3">
            <%= f.input :opinion_interview, label: "Avis entretien", class: 'form-control' %>
          </div>
          <div class="form-group mb-3">
            <%= f.input :is_passable, label: "Bon profile?", as: :boolean, class: 'form-control' %>
          </div>
          <div class="form-group mb-3">
            <%= f.input :opinion_internship, label: "Avis Stage", class: 'form-control' %>
          </div>
          <div class="form-group mb-3">
            <%= f.input :potential_internship, label: "Stage potentiel", class: 'form-control' %>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.button :submit, 'Ajouter', class: 'btn btn-raised btn-success' %>
          <button type="button" class="btn btn-raised btn-warning" data-dismiss="modal">Annuler</button>
        </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id='remote-container'></div>