config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq", as: :sidekiq

  resources :users, only: [:create, :update] do
    collection { post :import }
  end
  devise_scope :user do
    devise_for :users, :controllers => {:registrations => "my_devise/registrations"}
    resources :users, except: [:create, :update]

    
    get "/users/sign_up",  :to => 'welcomes#index'
   
    authenticated :user do
      root 'welcomes#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end   
  end

  get 'enable/:id' => 'users#enable', as: 'enable'
  get 'disable/:id' => 'users#pre_disable', as: 'pre_disable'
  post 'disable/:id' => 'users#disable', as: 'disable'
  get '/users/role/:title', to: 'users#users_by_role', as: :users_by_role

  resources :companies

  root 'welcomes#index'

  get '/export' => 'welcomes#export', as: 'export'
  get '/en-cours-developement' => 'welcomes#en_cours_devlopement', as: 'en_cours_devlopement'

  get '/start_load' =>  'load_updated_files#start_load', as: 'start_load'

  resources :fonctional_manager_externs do
    collection { post :import }
  end

  resources :furloughs
  get 'validate/:id' => 'furloughs#validate', as: 'validate'
  get 'approuve/:id' => 'furloughs#valide_fc', as: 'valide_fc'
  get 'in_progress/:id' => 'furloughs#in_progress', as: 'in_progress'
  get 'soumettre/:id' => 'furloughs#soumettre', as: 'soumettre'
  get 'mes-congés' => 'furloughs#furloughs_administration', as: 'furloughs_administration'
  get 'congé/:id' => 'furloughs#show_administration', as: 'show_administration'
  get 'refuse/:id' => 'furloughs#pre_refuse', as: 'pre_refuse'
  post 'refuse/:id' => 'furloughs#refuse', as: 'refuse'
  get 'cancel/:id' => 'furloughs#pre_cancel', as: 'pre_cancel'
  post 'cancel/:id' => 'furloughs#cancel', as: 'cancel'
  get 'print/:id' => 'furloughs#to_print', as: 'print'
  get 'findtypefurlough/:id' => 'furloughs#find_furlough_type', as: 'find_furlough_type'
  get 'getitemtohiligh/' => 'furloughs#get_item_to_hiligh', as: 'get_item_to_hiligh'
  get 'findfonctionalmanagerid/:name' => 'furloughs#find_fonctional_manager_id', as: 'find_fonctional_manager_id'
  get 'finduserid/:name' => 'furloughs#find_user_id', as: 'find_user_id'
  get 'findlinemanagerid/:name' => 'furloughs#find_line_manager_id', as: 'find_line_manager_id'
  get 'discontinuity/:id' => 'furloughs#pre_discontinuity', as: 'pre_discontinuity'
  post 'discontinuity/:id' => 'furloughs#discontinuity', as: 'discontinuity'
  get 'regularized/:id' => 'furloughs#pre_regularized', as: 'pre_regularized'
  post 'regularized/:id' => 'furloughs#regularized', as: 'regularized'
  get 'stop/:id' => 'furloughs#pre_stop', as: 'pre_stop'
  post 'stop/:id' => 'furloughs#stop', as: 'stop'
  get 'duration_hour_taken/:user_id/:start/:hour_start/:end/:hour_end' => 'furloughs#duration_hour_taken', as: 'duration_hour_taken'
  get 'duration_taken/:start/:hour_start/:end/:hour_end' => 'furloughs#durations_taken', as: 'duration_taken'

  resources :furlough_types do
    collection { post :import }
  end
  get 'enablefurloughtype/:id' => 'furlough_types#enable_furlough_type', as: 'enable_furlough_type'
  get 'disablefurloughtype/:id' => 'furlough_types#disable_furlough_type', as: 'disable_furlough_type'


  resources :offs do
    collection { post :import }
  end
  get 'adjust/:id' => 'offs#pre_adjust', as: 'pre_adjust'
  post 'adjust/:id' => 'offs#adjust', as: 'adjust'

  resources :additional_hours  
  get 'soumettreHeuresSup/:id' => 'additional_hours#soumettre_additional_hour', as: 'soumettre_additional_hour'
  get 'mes-heures-sup' => 'additional_hours#additional_hours_administration', as: 'additional_hours_administration'
  get 'period/:additional_hour_date' => 'additional_hours#get_period', as: 'get_period'
  get 'days_of_input_form/:period' => 'additional_hours#get_days_of_input_form', as: 'get_days_of_input_form'
  get 'valid_hours/:start/:hour_start/:end/:hour_end' => 'additional_hours#get_valid_hours', as: 'get_valid_hours'
  get 'export-heures-sup' => 'additional_hours#pre_export_additional_hours', as: 'pre_export_additional_hours'
  get 'export-heures-sup-lolo' => 'additional_hours#export_additional_hours', as: 'export_additional_hours'

  resources :autorizations 
  get 'soumettreAuthorization/:id' => 'autorizations#soumettre_autorization', as: 'soumettre_autorization'
  get 'mes-authorisations' => 'autorizations#authorizations_administration', as: 'authorizations_administration'
  get 'authorization_hour_taken/:user_id/:date/:start_hour/:end_hour' => 'autorizations#duration_hour_taken_of_authorization', as: 'duration_hour_taken_of_authorization'
  get 'export-authorizations' => 'autorizations#pre_export_authorizations', as: 'pre_export_authorizations'
  get 'export-authorizations-lolo' => 'autorizations#export_authorizations', as: 'export_authorizations'
  get 'recovered/:id' => 'autorizations#pre_recovered', as: 'pre_recovered'
  post 'recovered/:id' => 'autorizations#recovered', as: 'recovered'
  post 'create_for_a_collaborator' => 'autorizations#create_for_a_collaborator', as: 'create_for_a_collaborator'
  post 'create_for_himself' => 'autorizations#create_for_him_self', as: 'create_for_him_self'
  get 'printauthorisation/:id' => 'autorizations#to_print_authorisation', as: 'to_print_authorisation'
  get 'validateAuthorization/:id' => 'autorizations#validate_autorization', as: 'validate_autorization'
  get 'refuseAuthorization/:id' => 'autorizations#pre_refus', as: 'pre_refus'
  post 'refuseAuthorization/:id' => 'autorizations#refus_autorization', as: 'refus_autorization'

  resources :absence_types

  resources :absences
  get 'export-absences' => 'absences#pre_export_absences', as: 'pre_export_absences'
  get 'export-absences-lolo' => 'absences#export_absences', as: 'export_absences'

  resources :formation_types

  resources :formations

  resources :interns

  resources :certificate_requests
  get 'printAttestation/:id' => 'certificate_requests#to_print', as: 'print_attestation'
  get 'mes-demandes-attestations' => 'certificate_requests#certificate_requests_administration', as: 'certificate_requests_administration'
  get 'validate-attestation/:id' => 'certificate_requests#validate_certificate', as: 'validate_certificate'
  get 'certificate/:id' => 'certificate_requests#pre_certificate', as: 'pre_certificate'
  post 'certificate/:id' => 'certificate_requests#certificate', as: 'certificate'
  get 'refus-certificate/:id' => 'certificate_requests#pre_refus_certificate', as: 'pre_refus_certificate'
  post 'refuscertificate/:id' => 'certificate_requests#refus_certificate', as: 'refus_certificate'

  resources :projects
  get 'deleteproject/:id' => 'projects#delete_project', as: 'delete_c'
  get 'disableproject/:id' => 'projects#disable_project', as: 'disable_project'
  get 'enableproject/:id' => 'projects#enable_project', as: 'enable_project'
  get 'findprojectid/:name' => 'projects#find_project_id', as: 'find_project_id'
  get 'unarchiveproject/:id' => 'projects#unarchive_project', as: 'unarchive_project'

  resources :affectations
  get 'disaffectation/:id' => 'affectations#pre_disaffectation', as: 'pre_disaffectation'
  post 'disaffectation/:id' => 'affectations#disaffectation', as: 'disaffectation'
  get 'mes-affectations' => 'affectations#mes_affectations', as: 'mes_affectations'
  get 'disaffectation/:user_id/:project_id' => 'affectations#disaffectation_through_project', as: 'project_disaffectation'

  resources :costs
  get 'archivedcost' => 'costs#archived_cost', as: 'archived_cost'
  get 'disablecost/:id' => 'costs#disable_cost', as: 'disable_cost'
  get 'enablecost/:id' => 'costs#enable_cost', as: 'enable_cost'
  get 'findcostid/:name' => 'costs#find_cost_id', as: 'find_cost_id'
  get 'deletecost/:id' => 'costs#delete_cost', as: 'delete_cost'
  get 'unarchivecost/:id' => 'costs#unarchive_cost', as: 'unarchive_cost'
  get 'deleteproject/:id' => 'costs#delete_project', as: 'delete_project'

  resources :notes
  get 'mes-notes' => 'notes#mes_notes', as: 'mes_notes'
  get 'projects-by-user/:name' => 'notes#project_users', as: 'project_users'

  resources :stop_actions do
    collection { post :import }
  end

  resources :grounds do
    collection { post :import }
  end

  resources :user_confs
  
  resources :template_attestations

  resources :journals

  resources :settings
end

app/controllers/absence_types_controller.rb
class AbsenceTypesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_absence_type, only: %i[ show edit update destroy ]
  before_action :set_role, only: %i[ create update destroy ]

  # GET /absence_types
  def index
    @setting = Setting.find(1)
    @absence_types = AbsenceType.all
  end

  # GET /absence_types/1
  def show
  end

  # GET /absence_types/new
  def new
    @absence_type = AbsenceType.new
  end

  # GET /absence_types/1/edit
  def edit
  end

  # POST /absence_types
  def create
    @absence_type = AbsenceType.new(absence_type_params)

    if @absence_type.save
      Journal.create_journal(@role.title, current_user, "ajouté", "AbsenceType", "un nouveau type d'absence", @absence_type.name, @absence_type.id, "Created")
      redirect_to absence_types_path(@absence_type), success: "Le type d'absence a été créé avec succès."
    else
      redirect_to absence_types_path(@absence_type), danger: "#{@absence_type.errors.full_messages}"
    end
  end

  # PATCH/PUT /absence_types/1
  def update
    if @absence_type.update(absence_type_params)
      Journal.create_journal(@role.title, current_user, "modifié", "AbsenceType", "le type d'absence", @absence_type.name, @absence_type.id, "Updated")
      redirect_to absence_type_url(@absence_type), success: "Le type d'absence a été mis à jour avec succès."  
    else
      redirect_to absence_type_url(@absence_type), danger: "#{@absence_type.errors.full_messages}"
    end
  end

  # DELETE /absence_types/1
  def destroy
    result = @absence_type.destroy_absence_type
    if result[:flash_type] == "success"
      Journal.create_journal(@role.title, current_user, "supprimé", "AbsenceType", "le type d'absence", @absence_type.name, @absence_type.id, "Deleted")
      redirect_to absence_types_url, success: "#{result[:message]}."
    else
      redirect_to absence_types_url, danger: "#{result[:message]}."
    end
  end

  private
  
    def set_absence_type
      @absence_type = AbsenceType.find(params[:id])
    end

    def set_role
      @role = Role.find(current_user.role_id)
    end

    def absence_type_params
      params.require(:absence_type).permit(:code, :name)
    end
end

app/helpers/absence_types_helper.rb
module AbsenceTypesHelper
end

app/views/absence_types/_form.html.erb
<!-- Modal -->
<div class="modal fade" id="edit_absence_type" role="dialog">
    <%= simple_form_for @absence_type do |f| %>
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myLargeModalLabel">Modification de type d'absence</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-12">
                        <div class="form-group">
                            <%= f.input :name, label: 'Type de congé', placeholder: "Entrer le type d'absence", class: 'form-control' %>
                        </div>
                        <div class="form-group mb-3">
                            <%= f.input :code, label: 'Code de congé', placeholder: "Entrer le code de type d'absence", class: 'form-control' %>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <%= f.button :submit, 'Valider', class: 'btn btn-raised btn-success' %>
                <button type="button" class="btn btn-raised btn-danger" data-dismiss="modal">Annuler</button>
            </div>
        </div>
      </div>
    <% end %>
</div>

app/views/absence_types/_show.html.erb
<div class="modal fade" id="show_absence_type" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myLargeModalLabel">Detail de type d'absence</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <div class="card-box">
                    <h4 class="font-13 text-muted text-uppercase mb-2">Code :</h4>
                    <p class="mb-3"><%= @absence_type.code %></p>

                    <h4 class="font-13 text-muted text-uppercase mb-2">Absence :</h4>
                    <p class="mb-3"><%= @absence_type.name %></p>

                </div>    
            </div>

            <div class="modal-footer">
            
                <%= link_to edit_absence_type_path(@absence_type), remote: true, class: "btn btn-warning waves-effect waves-light" do %>
                    <i class="mdi mdi-border-color"></i>
                <% end %>

                <%= link_to @absence_type, method: :delete, data: { confirm: 'Etes vous sur?' }, title: "Suprimer", class: "btn btn-danger waves-effect waves-light" do %>
                    <i class="mdi mdi-delete"></i>
                <% end %>       
            </div>
      
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>



            

app/views/absence_types/edit.js.erb
$('#remote-container').html('<%= j render "absence_types/form" %>');
$('#edit_absence_type').modal('show');

app/views/absence_types/index.html.erb
<% provide(:title, 'absence-types') %>

<div class="content">

    <!-- Start Content-->
    <div class="container-fluid">
        
        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box">
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="<%= root_path %>">Accueil</a></li>
                            <li class="breadcrumb-item active">gestion des types d'absences</li>
                        </ol>
                    </div>
                    <h4 class="page-title">Liste des types d'absences</h4>
                </div>
            </div>
        </div>     
        <!-- end page title --> 


        <div class="row">
            <div class="col-12">
                <div class="card-box">
                  <div class="bg-light d-flex justify-content-between mb-2">
                    <div class="text-sm-center form-inline">
                      <div class="form-group mr-2">
                        <%= link_to '#new_absence_type', class: "btn btn-primary", :id => 'login', "data-toggle" => "modal", 'data-target' => '#new_absence_type'  do %>
                          <i class="mdi mdi-plus mr-1"> Nouveau Type d'absence</i>
                        <% end %>
                      </div>
                      <div class="form-group">
                        <input id="demo-input-search2" type="text" placeholder="Search" class="form-control" autocomplete="off">
                      </div>
                    </div>
                    <div>
                      <div class="col-lg-6">
                        <%#= form_tag import_furlough_types_path, multipart: true do %>
                        <%#= file_field_tag :file, required: true %>
                        <%#= submit_tag 'Importer', class: "btn btn-success waves-effect waves-light mr-3" %>
                        <%# end %>
                      </div>
                      <div class="col-lg-4">
                        <%#= form_tag furlough_types_path, :method => 'get',  class: "form-inline" do %>
                        <div class="form-group">
                          <%# if params[:search].present? %>
                          <%#= text_field_tag :search,nil, class:"form-control", value:"#{params[:search]}" %>
                          <%# else %>
                          <%#= text_field_tag :search,nil, class:"form-control", placeholder:"Trouvez une commande ... " %>
                          <%# end %>
                          <!--<button type="submit" class="btn btn-warning waves-effect waves-light ml-1"><i class="mdi mdi-magnify mr-1"></i> Cherche!</button>-->
                        </div>
                        <%# end %>
                      </div>
                    </div>
                  </div>
                  <table id="demo-foo-addrow" class="table table-centered table-striped table-bordered mb-0 toggle-circle" data-page-size="7">
                    <thead>
                    <tr>
                      <th data-sort-initial="true" data-toggle="true">Type d'absence </th>
                      <th data-hide="phone, tablet">Code </th>
                      <th data-hide="phone, tablet">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    <% @absence_types.each do |absence_type| %>
                      <tr>
                        <td><%= absence_type.name %></td>
                        <td><%= absence_type.code %></td>
                        <td>
                          <%= link_to absence_type_path(absence_type), remote: true, title: "Voir", class: "action-icon" do %>
                            <i class="mdi mdi-eye"></i>
                          <% end %>
                          <%= link_to edit_absence_type_path(absence_type), remote: true, title: "Modifier", class: "action-icon" do %>
                            <i class="mdi mdi-border-color"></i>
                          <% end %>
                          <%= link_to absence_type, method: :delete, data: { confirm: 'Etes vous sur?' }, title: "Suprimer", class: "action-icon" do %>
                            <i class="mdi mdi-delete"></i>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                    </tbody>
                    <tfoot>
                    <tr class="active">
                      <td colspan="8">
                        <div class="text-right">
                          <ul class="pagination pagination-split justify-content-end footable-pagination m-t-10"></ul>
                        </div>
                      </td>
                    </tr>
                    </tfoot>
                  </table>
                </div> <!-- end card-->
            </div> <!-- end col -->
        </div>
        <!-- end row -->
    </div>
    <div id='remote-container'></div>
</div> <!-- content -->

<!--  Modal content for the Large example -->
<div class="modal fade" id="new_absence_type" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myLargeModalLabel">Définition d'un type d'absence</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <%= simple_form_for(AbsenceType.new, as: :absence_type, method: :post, html: { class: "form-horizontal" }) do |f| %>
                
                <div class="modal-body">
                    <div class="form-group mb-3">
                        <%= f.input :name, label: "Type d'absence", placeholder: "Entrer le type d'absence", class: 'form-control' %>
                    </div>
                    <div class="form-group mb-3">
                        <%= f.input :code, label: "Code de type d'absence", placeholder: "Entrer le code de type d'absence", class: 'form-control' %>
                    </div>
                </div>
            
                <div class="modal-footer">
                    <%= f.button :submit, 'Ajouter', class: 'btn btn-raised btn-success' %>
                    <button type="button" class="btn btn-raised btn-warning" data-dismiss="modal">Annuler</button>
                </div>
            <% end %>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/absence_types/show.js.erb
$('#remote-container').html('<%= j render "absence_types/show" %>');
$('#show_absence_type').modal('show');